// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4sd_elHc1ZBQTHVw6-PJQODNU1XU4DmU',
    appId: '1:267892884533:web:3fc4a20b576c3ecfc15d7c',
    messagingSenderId: '267892884533',
    projectId: 'aiesec-lar-global',
    authDomain: 'aiesec-lar-global.firebaseapp.com',
    storageBucket: 'aiesec-lar-global.firebasestorage.app',
    measurementId: 'G-B0HKPE8NDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmAJzfky6BbdYQyKTe0plwp934JiYMeS4',
    appId: '1:267892884533:android:a2a0cb95aac90b63c15d7c',
    messagingSenderId: '267892884533',
    projectId: 'aiesec-lar-global',
    storageBucket: 'aiesec-lar-global.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDfTk6SiLexRndI1oX0L4mp9Hn6wBPsLg',
    appId: '1:267892884533:ios:6d9eb76fab3ab44bc15d7c',
    messagingSenderId: '267892884533',
    projectId: 'aiesec-lar-global',
    storageBucket: 'aiesec-lar-global.firebasestorage.app',
    iosBundleId: 'com.example.aiesecLarGlobal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDfTk6SiLexRndI1oX0L4mp9Hn6wBPsLg',
    appId: '1:267892884533:ios:6d9eb76fab3ab44bc15d7c',
    messagingSenderId: '267892884533',
    projectId: 'aiesec-lar-global',
    storageBucket: 'aiesec-lar-global.firebasestorage.app',
    iosBundleId: 'com.example.aiesecLarGlobal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4sd_elHc1ZBQTHVw6-PJQODNU1XU4DmU',
    appId: '1:267892884533:web:853bfe1cdcc40d54c15d7c',
    messagingSenderId: '267892884533',
    projectId: 'aiesec-lar-global',
    authDomain: 'aiesec-lar-global.firebaseapp.com',
    storageBucket: 'aiesec-lar-global.firebasestorage.app',
    measurementId: 'G-XMWN9XJNRB',
  );
}
